package gphelper;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.io.File;
import java.net.URI;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

public class JAboutDialog extends javax.swing.JDialog {

    public JAboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String version = getVersionfinal(parent.getClass());
        if (version.length() > 0) {
            version = "Date compiled : " + version;
        }
        setTitle("About gphelper");
        jLabelDescription.setText("GnuPG Helper");
        jLabelCopyright.setText("Copyright (c) 2013 Michel Valentin");
        jLabelVersion.setText(version);

        Rectangle parentBounds = parent.getBounds();
        Dimension size = getSize();
        int x = Math.max(0, parentBounds.x + (parentBounds.width - size.width) / 2);
        int y = Math.max(0, parentBounds.y + (parentBounds.height - size.height) / 2);
        setLocation(new Point(x, y));

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk = new javax.swing.JButton();
        jLabelDescription = new javax.swing.JLabel();
        jLabelCopyright = new javax.swing.JLabel();
        jLabelVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setResizable(false);

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescription.setText("Description");

        jLabelCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCopyright.setText("Copyright");

        jLabelVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersion.setText("Version");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jButtonOk, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(218, 218, 218))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCopyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelDescription)
                .addGap(29, 29, 29)
                .addComponent(jLabelCopyright)
                .addGap(29, 29, 29)
                .addComponent(jLabelVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

public String getVersionfinal (Class classe) {
	String version = null;
	String shortClassName = classe.getName().substring(classe.getName().lastIndexOf(".") + 1);
	try {
		ClassLoader cl = this.getClass().getClassLoader();
		String threadContexteClass = classe.getName().replace('.', '/');
		URL url = cl.getResource(threadContexteClass + ".class");
		if ( url == null ) {
			version = "";
		} else {
			String path = url.getPath();
			String jarExt = ".jar";
			int index = path.indexOf(jarExt);
			SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
			if (index != -1) {
				String jarPath = path.substring(0, index + jarExt.length());
				File file = new File(jarPath);
				String jarVersion = file.getName();
				JarFile jarFile = new JarFile(new File(new URI(jarPath)));
				JarEntry entry = jarFile.getJarEntry("META-INF/MANIFEST.MF");
				version = sdf.format(new Date(entry.getTime()));
				jarFile.close();
			} else {
				File file = new File(path);
				version = sdf.format(new Date(file.lastModified()));
			}
		}
	} catch (Exception e) {
		version = "";
	}
	return version;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelCopyright;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelVersion;
    // End of variables declaration//GEN-END:variables
}
